### ISSUE TITLE
Does not run in docker

### ISSUE THREAD

**Issue by jacobtomlinson** [met-office-lab/opsdroid-skill-aws-tag-compliance#1]
When running this skill in docker you get the following error.

```
ERROR opsdroid.parsers.regex: Exception when parsing 'update tags' against skill 'update( aws|ec2|instance)? tags'
Traceback (most recent call last):
  File "/usr/src/app/opsdroid/parsers/regex.py", line 27, in parse_regex
    await skill["skill"](opsdroid, skill["config"], message)
  File "/root/.opsdroid/modules/opsdroid-modules/skill/aws-tag-compliance/__init__.py", line 134, in update_tags
  File "/root/.opsdroid/modules/opsdroid-modules/skill/aws-tag-compliance/__init__.py", line 26, in get_instances
  File "/root/.opsdroid/site-packages/aiobotocore/session.py", line 66, in create_client
  File "/root/.opsdroid/site-packages/botocore/session.py", line 701, in get_component
  File "/root/.opsdroid/site-packages/botocore/session.py", line 897, in get_component
  File "/root/.opsdroid/site-packages/botocore/session.py", line 186, in create_default_resolver
  File "/root/.opsdroid/site-packages/botocore/loaders.py", line 132, in _wrapper
  File "/root/.opsdroid/site-packages/botocore/loaders.py", line 424, in load_data
botocore.exceptions.DataNotFoundError: Unable to load data for: endpoints
```

**Comment by jacobtomlinson** [comment]
This is now working as of implementing the fix in opsdroid/opsdroid#283.
